### location 리스트에서 하나의 포스트 선택 시에 대한 요청
GET {{domain-address}}/test-driving/7


### 최종적인 예약 요청 ver2
PATCH {{domain-address}}/appointments/2
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiZW1haWwiOiJ0ZXN0QHRlc3QuY29tIiwicm9sZSI6IkFUSyIsImlhdCI6MTY3NjUzMTU3NywiZXhwIjoxNjc2NTMzMzc3fQ.nNFWOu6uIeNHyiCXTOKwlJabelnouS0gAujDrKlL_0Q

###
POST {{domain-address}}/test-driving/posts
Content-Type: application/json

{
  "carName": "IONIC6",
  "dateList": [
  ],
  "optionList": [
  ]
}
