### 공유하기
POST http://localhost:8080/sharing
Content-Type: application/json

{
  "post": {
    "carName": "Santafe",
    "rideOption": "RIDE_WITH",
    "userId": 1,
    "requirement": "lotte v3"
  },
  "location": {
    "latitude": "37.5326",
    "longitude": "127.024612"
  },
  "options": [
    {
      "name": "d",
      "category": "옵션"
    },
    {
      "name": "e",
      "category": "모델"
    },
    {
      "name": "f",
      "category": "엔진"
    }
  ],
  "dates": [
    "2022-10-01",
    "2022-10-03",
    "2022-10-04"
  ]
}
