### 공유하기
POST http://localhost:8080/sharing
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwicm9sZSI6IkFUSyIsImlhdCI6MTY3NjQzNzEzOCwiZXhwIjoxNjc2NTIzNTM4fQ.viY5xrJhRQP3JcVljkxOUXUHEah4TZOnvautWNJC6Kc

{
  "post": {
    "carName": "Santafe-",
    "rideOption": "RIDE_WITH",
    "requirement": "lotte v3"
  },
  "location": {
    "latitude": "37.5326",
    "longitude": "127.024612"
  },
  "options": [
    {
      "name": "d",
      "category": "옵션"
    },
    {
      "name": "e",
      "category": "엔진"
    },
    {
      "name": "f",
      "category": "엔진"
    }
  ],
  "dates": [
    "2022-10-01",
    "2022-10-03",
    "2022-10-04"
  ]
}
