### 공유하기
POST {{domain-address}}/sharing
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiZW1haWwiOiJ0ZXN0QHRlc3QuY29tIiwicm9sZSI6IkFUSyIsImlhdCI6MTY3NjgyMDI3OSwiZXhwIjoxNjc2ODIyMDc5fQ.oAu0sByCpFTjklo-eU4iltSF1pNFCC2foNR83tobwGI

{
  "dates": [
    "2022-10-01",
    "2022-10-03"
  ],
  "location": {
    "latitude": "37.5326",
    "longitude": "127.02422"
  },
  "myCarId": 1,
  "requirement": "hello hello",
  "rideOption": "RIDE_ALONE"
}
