### 회원가입
POST {{domain-address}}/users
Content-Type: application/json

{
  "email": "test@test.com",
  "userPassword": "비밀번호",
  "userName": "tester",
  "phoneNumber": "010-1234-1234"
}

### 로그인
POST {{domain-address}}/login
Content-Type: application/json

{
  "email": "test@test.com",
  "userPassword": "비밀번호"
}

### test auth
GET {{domain-address}}/auth
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwicm9sZSI6IkFUSyIsImlhdCI6MTY3NjQ1NDc0MSwiZXhwIjoxNjc2NDU2NTQxfQ.ZZbgv1VgzyvdfzEbKGrmWqo1Q6_3cdWBXh1uLolG7wk
