### 회원가입
POST http://{{domain-address}}/users
Content-Type: application/json

{
  "email": "test@test.com",
  "userPassword": "비밀번호",
  "userName": "tester",
  "phoneNumber": "010-1234-1234"
}

### 로그인
POST http://{{domain-address}}/login
Content-Type: application/json

{
  "email": "test@test.com",
  "userPassword": "비밀번호"
}

### test auth
GET http://{{domain-address}}/test/auth
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIn0.R185SBLcwiUne4wqve5BEZbrFey96uxKwDC_xQu4qm0
